export interface HierarchyDatum {
  name: string;
  id: string;
  _leaf?: boolean;
  children?: HierarchyDatum[];
}

export const COLORS: Record<string, string> = {
  strategy: '#6c5ce7', digital: '#0984e3', content: '#e17055', analytics: '#00b894',
  brand: '#d63031', channels: '#00cec9', paid: '#e6a817', community: '#8e7ff7',
  physical: '#fd7f4a', product_growth: '#0097a7', lifecycle: '#c2185b',
  mobile: '#039be5', earned_media: '#6d4c41', growth_lab: '#388e3c',
  data_infra: '#37474f', ai_marketing: '#512da8', commerce: '#e64a19',
  demand_gen: '#1565c0', creator: '#ad1457', retail_media: '#558b2f',
};

export const DESCRIPTIONS: Record<string, string> = {
  marketing: 'A complete marketing operating system that shows how strategy, channels, content, measurement, lifecycle, product growth, and revenue work together. Use it to understand both what a team does and which tools or mechanics support each area.',
  strategy: 'The planning layer that decides who the business is for, where it will compete, how it will win, and what success looks like. This is the foundation that makes every other marketing decision more focused and effective.',
  icp: 'Ideal Customer Profile defines the type of customer that gets the most value from your offer and is most valuable to the business. It helps teams focus acquisition, messaging, product choices, and sales effort on the right audience.',
  gtm: 'Go-to-Market strategy is the plan for bringing a product or offer to the market successfully. It covers the target audience, positioning, pricing, channels, timing, and how marketing and sales will work together.',
  funnel: 'Funnel Design maps the steps a customer moves through from first awareness to conversion and beyond. It helps teams understand what each stage needs, where drop-offs happen, and which tactics should support each step.',
  compete: 'Competitive Intelligence is the process of tracking competitors, alternatives, and category signals to make smarter decisions. It helps teams spot gaps, defend positioning, and respond to market changes faster.',
  okr: 'OKRs and KPIs define what success looks like and how progress will be measured. They turn strategy into clear goals, targets, and metrics that teams can align around.',
  persona: 'Personas describe the main customer types a brand serves in a human, easy-to-understand way. They usually combine goals, pains, motivations, behaviours, and buying triggers to guide better messaging and experiences.',
  segmentation: 'Segmentation splits a broad market into smaller groups with shared characteristics, needs, or behaviours. This makes targeting, messaging, offers, and lifecycle journeys more relevant and efficient.',
  digital: 'The part of marketing that happens through websites, search engines, email, apps, and social platforms. It focuses on reaching people online, guiding them to take action, and improving performance over time.',
  seo: 'Search Engine Optimisation improves how easily people can find a website through unpaid search results. It combines technical fixes, content quality, authority signals, and search intent alignment.',
  sem: 'Search Engine Marketing uses paid ads on search platforms to capture demand when people are already looking for something. It is especially useful for intent-driven traffic, fast testing, and scalable acquisition.',
  email: 'Email Marketing uses targeted messages to educate, activate, retain, and re-engage subscribers or customers. It works best when messages are timely, segmented, and tied to a clear customer journey.',
  social: 'Social Media Marketing builds attention, engagement, and relationship through social platforms. It can support discovery, brand building, education, community, customer support, and sales.',
  social_mgmt: 'Social Management is the operational side of social media: planning, scheduling, publishing, moderating, and reporting. It helps teams stay consistent across platforms and measure what is working.',
  website: 'Website and UX focus on making digital experiences clear, useful, and conversion-friendly. This includes information architecture, design, copy, speed, testing, and the paths that lead users to action.',
  automation: 'Marketing Automation uses software to trigger messages, workflows, and actions based on rules or customer behaviour. It reduces manual work and makes journeys more consistent, scalable, and personalised.',
  crm: 'CRM systems organise customer and prospect information in one place so teams can manage relationships better. They support sales follow-up, segmentation, lifecycle marketing, reporting, and customer history.',
  affiliate: 'Affiliate Marketing grows reach and sales through partners who promote a brand in exchange for commission or reward. It is a performance-driven channel built on tracking, incentives, and partner relationships.',
  content: 'The ideas, stories, formats, and assets a brand publishes to attract attention, educate buyers, and build trust. Good content helps people understand the brand and gives them a reason to come back.',
  blog: 'Blogs and articles are written content designed to educate, answer questions, improve search visibility, and build trust. They are often used to attract organic traffic and support both thought leadership and conversion.',
  video: 'Video uses motion, sound, and storytelling to explain, demonstrate, entertain, or persuade. It is effective because it can communicate emotion, product value, and proof quickly.',
  podcast: 'Podcasts are audio-first content formats that help brands build authority, loyalty, and deeper audience attention. They are especially useful for interviews, expert commentary, and recurring content series.',
  ebooks: 'eBooks and reports are longer-form content assets that package knowledge into a more substantial format. They are often used for lead generation, thought leadership, internal education, or sales support.',
  ugc: 'User-Generated Content is content created by customers, fans, or community members rather than the brand itself. It adds authenticity, social proof, and relatable product usage examples.',
  webinar: 'Webinars are live or recorded online sessions used to educate an audience, answer questions, and capture demand. They work well for complex topics, B2B journeys, launches, and lead nurturing.',
  infographic: 'Infographics turn information, data, or processes into a visual format that is easier to scan and understand. They are useful when a topic is complex but needs to be explained quickly.',
  casestudy: 'Case studies show how a real customer used a product or service and what results they achieved. They are strong proof assets because they make value concrete and believable.',
  creator_pub: 'Creator platforms help individuals publish directly to an audience and often monetise that relationship. For marketers, they can be content channels, partnership surfaces, or creator-led media ecosystems.',
  short_video: 'Short-form video is quick, scroll-friendly video content built for high attention competition on social platforms. It is strong for reach, entertainment, education, trends, and repeated brand exposure.',
  live_stream: 'Live and streaming content creates real-time interaction between a brand and its audience. It is useful for launches, Q&As, events, demos, and community engagement because it feels immediate and unscripted.',
  analytics: 'The measurement layer that tracks what is happening, why it is happening, and where performance can improve. It turns data into practical decisions about spend, conversion, retention, and growth.',
  attribution: 'Attribution identifies which marketing touchpoints influenced a conversion, sale, or other result. It helps teams understand where value is coming from and how to allocate budget more intelligently.',
  cro: 'Conversion Rate Optimisation improves the percentage of visitors who take a desired action, such as signing up or buying. It uses testing, behavioural insight, and UX improvements to remove friction.',
  dataviz: 'Dashboards and data visualisation make performance data easier to read, compare, and act on. They help teams spot trends, communicate results, and make decisions faster.',
  cohort: 'Cohort analysis compares groups of users who share a common starting point, such as signup month or acquisition source. It is especially useful for understanding retention, repeat behaviour, and lifetime value over time.',
  cltv: 'Customer Lifetime Value analysis estimates how much revenue a customer is likely to generate over the full relationship. It helps shape acquisition budgets, retention priorities, and segmentation decisions.',
  heatmap: 'Heatmaps and session behaviour tools show how people actually interact with a page or interface. They reveal friction, hidden confusion, and missed opportunities that standard analytics can miss.',
  revenue: 'Revenue analytics connects marketing activity to pipeline, sales, subscription growth, and closed revenue. It helps teams move beyond vanity metrics and prove commercial impact.',
  brand: 'The layer that shapes how people recognise, remember, and feel about a company. It includes identity, voice, reputation, proof, and the signals that make a brand distinctive and trustworthy.',
  identity: 'Visual Identity is the set of visible brand elements that make a company recognisable, such as logo, colour, typography, layout, imagery, and design rules. It helps a brand look consistent and memorable across every touchpoint.',
  voice: 'Brand Voice defines how a company sounds when it speaks. It gives teams a clear style for writing and communication so the brand feels coherent, human, and recognisable wherever it appears.',
  pr: 'PR and Communications manage the stories, messages, and external relationships that shape public perception. This includes press outreach, announcements, reactive communications, and reputation management.',
  events: 'Events create planned moments where people can experience the brand directly, whether online or offline. They can build awareness, trust, community, product understanding, and relationship depth.',
  collab: 'Partnerships bring two or more brands, organisations, or communities together for shared value. They can unlock borrowed trust, audience access, richer offers, and more efficient growth.',
  storytelling: 'Storytelling turns a brand, product, or customer problem into a narrative people can understand and remember. It helps marketing feel more meaningful than a list of features or claims.',
  trust: 'Trust and Proof are the signals that reduce doubt and make people feel safe choosing a brand. This includes reviews, ratings, testimonials, certifications, case studies, and other credibility markers.',
  cultural_mktg: 'Cultural Marketing connects a brand to moments, behaviours, or conversations that already matter to people. When done well, it helps the brand feel relevant without losing its core identity.',
  channels: 'The distribution paths through which a brand reaches people. This layer maps where attention comes from, how messages travel, and which surfaces drive discovery, engagement, and conversion.',
  organic: 'Organic Search is traffic and visibility earned through unpaid search results. It depends on useful content, technical quality, and matching what people are actually searching for.',
  direct: 'Direct traffic comes from people who intentionally go to a brand without relying on another discovery source first. It often signals brand familiarity, repeat interest, or strong recall.',
  referral: 'Referral traffic comes from other websites, creators, publishers, or platforms sending people to your brand. It is a useful channel for discovery, authority building, and partnership-driven growth.',
  push: 'Push and SMS are direct messaging channels that reach people on their device with timely updates or prompts. They work best for urgent, personalised, or behaviour-triggered communication.',
  influencer: 'Influencer channels use trusted individuals to introduce, explain, or recommend a brand to their audience. This can drive awareness, credibility, content creation, and sales.',
  marketplace: 'Marketplaces are third-party platforms where people discover, compare, and buy products or services. They matter because the brand competes inside someone else\'s ecosystem and ranking logic.',
  msg_apps: 'Messaging apps are private, conversational spaces where brands can communicate one-to-one or one-to-many. They can support support, sales, community, updates, and direct relationship building.',
  chat: 'Chat and support channels help people ask questions and get help in the moment. They reduce friction, improve conversion confidence, and support customer satisfaction after purchase.',
  broadcast_ch: 'Broadcast channels are one-to-many communication surfaces inside platforms where people have opted in to receive updates. They are useful for repeat reach without depending fully on feed algorithms.',
  social_disc: 'Social discovery is when people find brands through search, conversations, recommendations, or content inside social platforms. It reflects the shift from traditional search to social-led discovery behaviour.',
  video_platforms: 'Video platforms are distribution environments where video is the main content format and discovery engine. They can support education, entertainment, community, product demos, and creator collaboration.',
  dark_social: 'Dark social describes private sharing that is hard to measure directly, such as links passed in chats, DMs, or closed groups. It often drives meaningful traffic and word of mouth even when attribution looks unclear.',
  emerging_ch: 'Emerging channels are newer or fast-changing platforms that may offer early attention and cheaper reach. They are useful for testing where audience behaviour is moving next.',
  paid: 'Marketing activity that uses budget to buy reach, traffic, visibility, or demand. It includes advertising formats and placements that can scale quickly when targeting, creative, and measurement are strong.',
  ppc: 'PPC and paid search place ads in search results so a brand can capture high-intent demand. It is valuable when speed, precision targeting, and measurable return matter.',
  social_ads: 'Social ads use paid placement inside social platforms to reach audiences based on interests, behaviours, demographics, or intent signals. They are often used for discovery, retargeting, and creative testing.',
  display: 'Display and banner advertising uses visual ad units across websites and apps to build awareness or drive action. It can support broad reach, remarketing, and programmatic audience targeting.',
  retargeting: 'Retargeting shows ads to people who have already interacted with a brand, product, or website. It helps recover lost demand and move interested users closer to conversion.',
  native: 'Native ads are paid placements designed to match the look and feel of the surrounding platform or publisher environment. They can feel less disruptive and work well for content-led promotion.',
  ott: 'OTT and CTV advertising reaches people through streamed television and connected devices rather than traditional broadcast TV. It combines video storytelling with more modern targeting and measurement.',
  sponsorship: 'Sponsorships give a brand visibility through association with an event, media property, team, creator, or programme. They are useful for borrowed credibility, awareness, and audience alignment.',
  community: 'The part of marketing focused on building ongoing relationships with customers, fans, advocates, and members. A strong community creates repeat engagement, referrals, feedback, and word of mouth.',
  forum: 'Community platforms are dedicated spaces a brand can use to host discussions, resources, and member interaction. They help create recurring engagement in an environment the brand can shape more directly.',
  social_communities: 'Social communities are groups or spaces inside existing social platforms where people gather around a topic, identity, or shared interest. Brands can participate there to listen, support, and build belonging.',
  advocacy: 'Brand advocate programs identify and support customers who are willing to recommend the brand publicly. These people can become a powerful source of trust, reviews, referrals, and user insight.',
  loyalty: 'Loyalty and rewards programs encourage repeat purchase and stronger customer relationships by offering benefits, points, perks, or recognition. They are designed to increase retention and customer value.',
  nps: 'NPS and CSAT measure how customers feel about their experience and how likely they are to recommend the brand. They help teams track sentiment, identify friction, and prioritise improvement.',
  ambassador: 'Ambassador programs formalise relationships with enthusiastic supporters who represent the brand more consistently over time. They often combine community, content, events, and referral value.',
  referral_prog: 'Referral programs reward existing customers or members for bringing in new people. They turn satisfaction and word of mouth into a more structured acquisition engine.',
  physical: 'Offline and real-world brand activity, from retail and packaging to events and outdoor media. It creates tangible experiences that people can see, touch, remember, and often share.',
  sampling: 'Product sampling gets a product into people\'s hands so they can experience it before making a bigger commitment. It is especially useful when the product benefits from trial, taste, touch, or immediate proof.',
  retail: 'Retail store marketing focuses on how a product is presented and discovered inside third-party physical stores. Shelf visibility, placement, signage, and shopper experience all influence performance.',
  brand_store: 'Brand retail refers to owned or heavily controlled physical retail environments that express the brand more fully. These spaces can drive sales while also shaping perception and loyalty.',
  popup: 'Pop-up shops are temporary retail or experience spaces created for speed, attention, and flexibility. They are useful for launches, collaborations, testing locations, and creating buzz.',
  festivals: 'Festival marketing places the brand inside high-energy live events where attention, participation, and cultural relevance are strong. It often works through sampling, activations, and memorable experiences.',
  ooh: 'Out-of-home and billboard advertising reaches people in public spaces such as streets, stations, and transport routes. It is effective for broad visibility, local presence, and distinctive creative.',
  experiential: 'Experiential marketing creates immersive or participatory brand experiences rather than just delivering a message. The goal is to make the brand felt, remembered, and shared.',
  dooh: 'Digital out-of-home uses digital screens in public spaces for dynamic, often more targetable outdoor advertising. It makes outdoor media more flexible, timely, and measurable than static placements.',
  direct_mail: 'Direct mail sends physical marketing materials directly to a person\'s home or business. It can stand out because it is tangible, targeted, and often less crowded than digital channels.',
  trade_show: 'Trade shows gather buyers, partners, competitors, and media in one place around a category or industry. They can support lead generation, relationship building, launches, and market visibility.',
  in_store_exp: 'In-store experience covers the physical moments that shape how shoppers interact with a brand at the shelf or in the store. Good execution can increase attention, trial, and conversion.',
  packaging: 'Packaging is both a functional product container and a marketing surface. It can communicate value, create differentiation, improve unboxing, and extend the brand experience into the home.',
  guerrilla: 'Guerrilla marketing uses unconventional, surprising, or low-cost tactics to generate disproportionate attention. It relies on creativity, shareability, and a strong idea more than media budget.',
  product_growth: 'The area where product and marketing meet to improve activation, adoption, retention, and expansion. It uses in-product journeys and growth mechanics to move users toward long-term value.',
  plg_mech: 'PLG mechanics are product-led growth systems that encourage users to discover value through the product itself. They often use usage triggers, sharing behaviour, and built-in loops to drive growth.',
  onboarding: 'Onboarding helps new users understand the product, reach their first meaningful success, and build confidence quickly. Strong onboarding improves activation, retention, and long-term adoption.',
  feature_adopt: 'Feature adoption focuses on getting users to discover, try, and repeat the product behaviours that matter most. It helps a team move users from basic usage to deeper value.',
  product_msg_tactic: 'In-product messaging uses prompts, banners, modals, tooltips, or embedded guidance inside the product experience. It helps users notice updates, take action, and stay engaged without leaving the product.',
  release_mktg: 'Release marketing communicates new features, changes, or launches in a way users can understand and care about. It turns product updates into clear customer value rather than internal product news.',
  growth_loops: 'Growth loops are repeatable systems where each user action creates conditions for more growth, such as referrals, shared content, or network effects. They are powerful because they can compound over time.',
  activation: 'Activation optimisation improves the moments that turn a new signup or visitor into a genuinely engaged user. It focuses on first value, friction reduction, and the early signals that predict retention.',
  freemium_tactic: 'Freemium strategy decides what is free, what is paid, and how users experience the path between them. It balances growth, product value, monetisation, and upgrade motivation.',
  lifecycle: 'Marketing across the full customer journey after acquisition, from onboarding to retention, upsell, renewal, and win-back. The goal is to keep customers engaged and grow their value over time.',
  lifecycle_strat_tactic: 'Lifecycle strategy defines the stages customers move through and what marketing should do at each stage. It gives teams a clear model for when to educate, remind, upsell, or re-engage.',
  retention_tactic: 'Retention marketing keeps existing customers active, satisfied, and connected to the product or brand. It focuses on repeat usage, habit formation, relationship strength, and churn reduction.',
  winback_tactic: 'Win-back campaigns are designed to re-engage people who became inactive, lapsed, or cancelled. They usually combine timing, relevance, and a clear reason to return now.',
  upsell_tactic: 'Upsell and cross-sell programs increase customer value by introducing a better plan, complementary product, or broader use case. They work best when the offer feels helpful rather than forced.',
  churn_prev_tactic: 'Churn prevention identifies risk signals early and intervenes before a customer leaves. It often combines health scoring, support, education, and recovery flows.',
  cust_edu_tactic: 'Customer education helps people get more value from what they already bought. It reduces confusion, supports adoption, and often improves retention and expansion.',
  sub_lifecycle_tactic: 'Subscription lifecycle marketing manages the moments that matter in recurring revenue models, such as renewal, pause, downgrade, and save flows. It aims to protect revenue while keeping the customer relationship healthy.',
  mobile: 'Marketing designed specifically for mobile apps and mobile-first user behaviour. It covers app discovery, install growth, onboarding, engagement, attribution, and retention.',
  aso_tactic: 'App Store Optimisation improves how well an app is discovered and chosen inside app stores. It combines keywords, creative assets, ratings, and listing strategy to increase installs.',
  app_install_tactic: 'App install ads are paid campaigns designed specifically to drive app downloads and qualified first opens. They matter when growth depends on efficient user acquisition at scale.',
  in_app_msg_tactic: 'In-app messaging on mobile uses messages inside the app to guide, remind, educate, or re-engage users. It can improve activation, retention, and response to key moments.',
  deep_link_tactic: 'Deep linking sends users to the exact screen, product, or step inside an app instead of just the home screen. This reduces friction and improves conversion from campaigns, content, or referrals.',
  mobile_attr_tactic: 'Mobile attribution shows which campaigns, channels, and touchpoints led to installs, opens, and downstream actions in an app. It is essential for understanding paid efficiency and lifecycle performance.',
  app_retention_tactic: 'App retention focuses on bringing users back and keeping the app part of their routine. It combines re-engagement messaging, product value reminders, and behavioural triggers.',
  mobile_onboard_tactic: 'Mobile onboarding helps new app users understand the value of the app and complete the right first actions quickly. Good onboarding improves retention far more than simply getting more installs.',
  earned_media: 'Visibility a brand earns rather than buys, such as press coverage, expert quotes, guest appearances, and rankings. It works through credibility, relationships, and newsworthy ideas.',
  editorial_tactic: 'Editorial placements secure coverage within publisher content rather than paid ad slots. They help a brand appear more credible because the message is carried by a third-party voice.',
  expert_comment_tactic: 'Expert commentary turns internal knowledge into quotes, insights, and perspectives that media or audiences can use. It helps a brand earn authority by being useful, not just promotional.',
  thought_lead_tactic: 'Thought leadership shares original perspectives, frameworks, or observations that help a market think differently. Done well, it builds trust, category authority, and top-of-mind relevance.',
  pod_guesting_tactic: 'Podcast guesting places a founder, operator, or expert in someone else\'s show to reach a relevant audience through conversation. It often creates long-form trust and reusable content.',
  media_partner_tactic: 'Media partnerships are structured collaborations with publishers or media brands for research, content, distribution, or co-branded visibility. They combine reach with borrowed credibility.',
  awards_tactic: 'Awards and rankings create external validation that can strengthen credibility with buyers, partners, and talent. They are especially useful when recognition aligns with what the market already values.',
  analyst_rel_tactic: 'Analyst relations build visibility and trust with influential industry analysts who shape category perception and buyer confidence. It is especially important in complex or high-consideration B2B markets.',
  growth_lab: 'A structured experimentation layer for finding non-obvious growth opportunities. It focuses on testing ideas fast, learning from results, and building repeatable growth systems.',
  north_star_tactic: 'A North Star Metric is the single metric that best reflects the value customers get from the product. It helps teams align around meaningful growth instead of scattered vanity metrics.',
  viral_mech_tactic: 'Viral mechanics are the built-in reasons people naturally share, invite, or bring others into a product or experience. They turn user behaviour into acquisition without relying only on paid media.',
  growth_sprint_tactic: 'Growth sprints are short, focused cycles for testing ideas quickly and learning what drives results. They help teams move from discussion to action with a clear time box and decision rhythm.',
  exp_tracking_tactic: 'Experiment tracking is the discipline of documenting hypotheses, tests, results, and learnings in a structured way. It prevents repeated mistakes and helps knowledge compound across the team.',
  rapid_test_tactic: 'Landing page tests are fast experiments on page structure, messaging, offers, or calls to action. They help teams learn what increases response before rolling changes out more widely.',
  msg_test_tactic: 'Messaging experiments compare different ways of explaining value, framing problems, or asking for action. They help teams find language that resonates more clearly with the target audience.',
  channel_exp_tactic: 'Mix modelling estimates how different channels contribute to outcomes when attribution is incomplete or fragmented. It helps teams make smarter budget decisions at portfolio level.',
  data_infra: 'The data foundation that makes modern marketing measurable and usable. It includes collection, storage, identity, governance, privacy, and the systems that keep customer data reliable.',
  cdp_tactic: 'A Customer Data Platform brings customer data from different systems into a more unified profile that marketing and product teams can use. It makes segmentation, activation, and personalisation more practical.',
  warehouse_tactic: 'A data warehouse stores large amounts of structured data in one central place for analysis and reporting. It gives teams a reliable source of truth across tools and departments.',
  identity_res_tactic: 'Identity resolution connects signals from different devices, channels, or records back to the same person or account where possible. This makes customer understanding and measurement more accurate.',
  event_track_tactic: 'Event tracking records important user actions such as clicks, signups, purchases, or feature use. It creates the raw behavioural data needed for product, marketing, and lifecycle analysis.',
  server_track_tactic: 'Server-side tracking sends data from backend systems rather than relying only on the browser or app client. It can improve reliability, privacy control, and measurement resilience.',
  privacy_mgmt_tactic: 'Privacy and consent management make sure customer data is collected and used in a compliant, transparent, and controlled way. This protects both the business and customer trust.',
  data_catalog_tactic: 'Data governance defines how data is named, documented, controlled, and maintained over time. It helps teams trust the data they use and reduces confusion across systems.',
  ai_marketing: 'Marketing capabilities powered or accelerated by AI, from content and targeting to prediction and support. It helps teams move faster, personalise better, and automate more complex decisions.',
  ai_content_tactic: 'AI content generation uses models to help draft, adapt, summarise, or scale content production. It can speed up workflows, but still needs human judgment for quality, originality, and brand fit.',
  ai_media_tactic: 'AI media buying uses automated systems to optimise targeting, bidding, budget allocation, or creative selection. It helps campaigns react faster to performance signals at scale.',
  ai_personal_tactic: 'AI personalisation uses behavioural, transactional, or contextual data to tailor experiences, messages, or offers to different users. The goal is to make marketing feel more relevant and timely.',
  ai_seg_tactic: 'AI segmentation finds patterns in customer data that help create more useful audience groups. It can surface clusters or behaviours that manual segmentation might miss.',
  predictive_tactic: 'Predictive analytics uses historical data to estimate what is likely to happen next, such as conversion probability, churn risk, or lead quality. It helps teams act earlier and prioritise better.',
  ai_support_tactic: 'AI customer support uses automation and language models to answer questions, route requests, and reduce service load. It can improve speed and coverage when paired with good escalation design.',
  ai_creative_tactic: 'AI creative testing helps teams generate, compare, and learn from multiple creative variations faster. It is useful for increasing testing volume and spotting which ideas deserve human refinement.',
  ai_recommend_tactic: 'AI recommendations suggest products, content, or next actions based on user behaviour and patterns across similar users. They are widely used to improve conversion, basket size, and retention.',
  commerce: 'The part of marketing focused on revenue conversion, merchandising, pricing, checkout, offers, and repeat purchase. Its job is to turn attention and intent into actual sales.',
  conv_strat_tactic: 'Conversion strategy defines how a commerce experience moves a visitor from interest to purchase with as little friction as possible. It combines page structure, proof, offer design, and decision support.',
  merchandising_tactic: 'Merchandising decides how products are organised, prioritised, and presented to increase relevance and sales. It shapes what shoppers notice first and how easily they find the right option.',
  pricing_com_tactic: 'Pricing strategy decides how an offer is priced, packaged, and framed in the market. It affects conversion, margin, positioning, and how customers perceive value.',
  promotions_tactic: 'Promotions are short-term incentives used to trigger purchase behaviour, clear stock, increase basket size, or create urgency. They work best when aligned with margins and broader brand strategy.',
  bundles_tactic: 'Bundles and offers combine products or benefits in a way that increases perceived value and purchase motivation. They can improve average order value while simplifying the decision.',
  checkout_opt_tactic: 'Checkout optimisation removes barriers in the final step of purchase, such as complexity, distrust, or unnecessary fields. Small improvements here can unlock significant revenue gains.',
  sub_strategy_tactic: 'Subscription strategy designs how recurring offers are structured, sold, retained, and expanded over time. It balances convenience, value delivery, flexibility, and revenue predictability.',
  marketplace_opt_tactic: 'Marketplace optimisation improves how a brand performs inside third-party commerce platforms. It covers listings, reviews, paid visibility, content, and conversion within marketplace rules.',
  demand_gen: 'B2B growth programs built to create awareness, qualified interest, and pipeline. It connects marketing and sales through account targeting, lead quality, enablement, and deal support.',
  abm_tactic: 'Account-based marketing focuses marketing and sales effort on a defined set of high-value accounts rather than a broad audience. It is designed for relevance, coordination, and deeper deal quality.',
  intent_data_tactic: 'Intent data uses behavioural signals to identify which companies or buyers may be actively researching a problem or solution. It helps teams prioritise accounts and time outreach more effectively.',
  sales_enable_tactic: 'Sales enablement gives revenue teams the content, training, proof, and tools they need to sell more effectively. It makes marketing more useful closer to the deal.',
  lead_scoring_tactic: 'Lead scoring ranks prospects based on fit and behaviour so teams know who is most ready or valuable to pursue. It helps improve handoff quality between marketing and sales.',
  sdr_support_tactic: 'SDR support equips outbound and follow-up teams with data, sequencing, targeting, and messaging tools. It improves prospecting efficiency and the quality of first-touch outreach.',
  pipeline_mktg_tactic: 'Pipeline marketing supports active opportunities, not just top-of-funnel lead generation. It helps move deals forward through tailored proof, stakeholder education, and account-specific programs.',
  field_mktg_tactic: 'Field marketing brings demand generation closer to specific regions, account groups, or local buying communities. It often combines events, partner activity, and more targeted relationship-building.',
  creator: 'A marketing layer built around creators as distribution, trust, and commerce partners. It includes partnerships, licensing, whitelisting, creator-led content, and creator commerce ecosystems.',
  retail_media: 'Advertising inside retailer-owned ecosystems such as Amazon, Walmart, or Instacart. It helps brands win visibility close to the point of purchase, where buying intent is already high.',
};

export const TAG_FAMILIES = {
  category: 'category',
  tactic: 'tactic',
  tech_solution: 'tech_solution',
  general_tool: 'general_tool',
  workflow: 'workflow',
  framework: 'framework',
  channel_surface: 'channel_surface',
  content_format: 'content_format',
  metric: 'metric',
} as const;

export type TagFamily = typeof TAG_FAMILIES[keyof typeof TAG_FAMILIES];

// Use this helper layer to avoid mixing vendor names with execution mechanics.
// Example: "HubSpot" => tech_solution, "email welcome flow" => workflow.
export const TAG_TYPE_EXAMPLES: Record<string, TagFamily> = {
  hubspot: 'tech_solution',
  hubspot_auto: 'tech_solution',
  hubspot_email: 'tech_solution',
  hubspot_crm: 'tech_solution',
  klaviyo: 'tech_solution',
  salesforce: 'tech_solution',
  marketo: 'tech_solution',
  email_welcome_flow: 'workflow',
  onboard_email: 'workflow',
  winback_series: 'workflow',
  renewal_emails: 'workflow',
  email_upsell: 'workflow',
  cart_recovery: 'workflow',
  cancel_flow: 'workflow',
  jtbd: 'framework',
  rfm: 'framework',
  tofu: 'framework',
  mofu: 'framework',
  bofu: 'framework',
  ig_reels: 'channel_surface',
  yt_shorts: 'channel_surface',
  tiktok_search: 'channel_surface',
  telegram_ch: 'channel_surface',
  tiktok_format: 'content_format',
  webinar_edu: 'content_format',
  health_score: 'metric',
  north_star_metric: 'metric',
};


function t(name: string, id: string): HierarchyDatum { return { name, id, _leaf: true }; }

export const DATA: HierarchyDatum = {
  name: 'Marketing\nSystem', id: 'marketing', children: [
    {
      name: 'Strategy', id: 'strategy', children: [
        { name: 'ICP', id: 'icp', children: [t('Jobs-to-\nbe-Done', 'jtbd'), t('Win/Loss\nInterviews', 'winloss'), t('Firmographics', 'firmographics'), t('Buyer\nSurveys', 'buyer_survey')] },
        { name: 'Go-to-Market', id: 'gtm', children: [t('Sales\nPlaybook', 'sales_playbook'), t('Channel\nMix', 'channel_mix'), t('Pricing', 'pricing'), t('Launch\nTimeline', 'launch_timeline')] },
        { name: 'Funnel\nDesign', id: 'funnel', children: [t('TOFU', 'tofu'), t('MOFU', 'mofu'), t('BOFU', 'bofu'), t('PLG Loop', 'plg_concept')] },
        { name: 'Competitive\nIntel', id: 'compete', children: [t('Crayon', 'crayon'), t('Klue', 'klue'), t('SEMrush', 'semrush_comp'), t('G2 Reviews', 'g2_reviews')] },
        { name: 'OKRs &\nKPIs', id: 'okr', children: [t('Notion', 'notion'), t('Lattice', 'lattice'), t('Perdoo', 'perdoo'), t('Workboard', 'workboard')] },
        { name: 'Personas', id: 'persona', children: [t('Xtensio', 'xtensio'), t('HubSpot\nPersona', 'hubspot_persona'), t('User\nInterviews', 'user_interviews'), t('Survey\nResearch', 'survey_research')] },
        { name: 'Segmentation', id: 'segmentation', children: [t('RFM\nModel', 'rfm'), t('Firmographic', 'firmographic_seg'), t('Behavioural', 'behavioural_seg'), t('Demographic', 'demographic_seg')] },
      ]
    },
    {
      name: 'Digital', id: 'digital', children: [
        { name: 'SEO', id: 'seo', children: [t('Ahrefs', 'ahrefs'), t('Search\nConsole', 'search_console'), t('Screaming\nFrog', 'screaming_frog'), t('SEMrush', 'semrush_seo')] },
        { name: 'SEM', id: 'sem', children: [t('Search\nIntent', 'search_intent'), t('Quality\nScore', 'quality_score'), t('Smart\nBidding', 'smart_bidding'), t('Keyword\nPlanner', 'keyword_planner')] },
        { name: 'Email', id: 'email', children: [t('Klaviyo', 'klaviyo'), t('Mailchimp', 'mailchimp'), t('HubSpot\nEmail', 'hubspot_email'), t('Drip', 'drip')] },
        { name: 'Social\nMedia', id: 'social', children: [t('Instagram', 'ig_platform'), t('TikTok', 'tiktok_platform'), t('LinkedIn', 'li_platform'), t('YouTube', 'yt_organic'), t('Facebook', 'fb_platform'), t('X / Twitter', 'x_platform'), t('Pinterest', 'pinterest_platform'), t('Snapchat', 'snapchat_platform'), t('Reddit', 'reddit_platform'), t('Threads', 'threads_platform')] },
        { name: 'Social\nManagement', id: 'social_mgmt', children: [t('Buffer', 'buffer'), t('Hootsuite', 'hootsuite'), t('Later', 'later'), t('Sprout\nSocial', 'sprout_social')] },
        { name: 'Website\n& UX', id: 'website', children: [t('Webflow', 'webflow'), t('Figma', 'figma'), t('Split.io', 'split_io'), t('Hotjar', 'hotjar_ux')] },
        { name: 'Automation', id: 'automation', children: [t('HubSpot', 'hubspot_auto'), t('Marketo', 'marketo'), t('ActiveCampaign', 'activecampaign'), t('Zapier', 'zapier')] },
        { name: 'CRM', id: 'crm', children: [t('Salesforce', 'salesforce'), t('HubSpot\nCRM', 'hubspot_crm'), t('Pipedrive', 'pipedrive'), t('Attio', 'attio')] },
        { name: 'Affiliate', id: 'affiliate', children: [t('Impact', 'impact'), t('ShareASale', 'shareasale'), t('PartnerStack', 'partnerstack'), t('Rakuten', 'rakuten')] },
      ]
    },
    {
      name: 'Content', id: 'content', children: [
        { name: 'Blog &\nArticles', id: 'blog', children: [t('WordPress', 'wordpress'), t('Ghost', 'ghost'), t('Contentful', 'contentful'), t('SEO Brief', 'seo_brief')] },
        { name: 'Video', id: 'video', children: [t('Adobe\nPremiere', 'premiere'), t('CapCut', 'capcut'), t('DaVinci\nResolve', 'davinci'), t('Final Cut', 'final_cut')] },
        { name: 'Podcast', id: 'podcast', children: [t('Spotify', 'spotify_pod'), t('Riverside.fm', 'riverside'), t('Buzzsprout', 'buzzsprout'), t('Apple\nPodcasts', 'apple_pod')] },
        { name: 'eBooks &\nReports', id: 'ebooks', children: [t('Canva', 'canva'), t('InDesign', 'adobe_id'), t('Gated\nPage', 'gated_page'), t('Ungated\nPDF', 'ungated_pdf')] },
        { name: 'UGC', id: 'ugc', children: [t('IG Reposts', 'ig_repost'), t('TikTok\nStitch', 'tiktok_stitch'), t('Review\nContent', 'review_ugc'), t('UGC\nContests', 'ugc_contest')] },
        { name: 'Webinars', id: 'webinar', children: [t('Zoom', 'zoom_web'), t('Demio', 'demio'), t('ON24', 'on24'), t('Hopin', 'hopin')] },
        { name: 'Infographics', id: 'infographic', children: [t('Datawrapper', 'datawrapper'), t('Piktochart', 'piktochart'), t('Visme', 'visme'), t('Adobe\nExpress', 'adobe_express')] },
        { name: 'Case\nStudies', id: 'casestudy', children: [t('Customer\nInterviews', 'customer_int'), t('ROI\nCalculator', 'roi_calc'), t('PDF\nFormat', 'pdf_case'), t('Video\nStory', 'video_story')] },
        { name: 'Creator\nPlatforms', id: 'creator_pub', children: [t('Substack', 'substack_pub'), t('Beehiiv', 'beehiiv'), t('Patreon', 'patreon_pub'), t('Medium', 'medium_pub')] },
        { name: 'Short-Form\nVideo', id: 'short_video', children: [t('Instagram\nReels', 'ig_reels'), t('YouTube\nShorts', 'yt_shorts'), t('TikTok\nFormat', 'tiktok_format'), t('Snapchat\nSpotlight', 'snap_spotlight')] },
        { name: 'Live &\nStreaming', id: 'live_stream', children: [t('Twitch', 'twitch_stream'), t('YouTube\nLive', 'yt_live'), t('Instagram\nLive', 'ig_live'), t('LinkedIn\nLive', 'li_live')] },
      ]
    },
    {
      name: 'Analytics', id: 'analytics', children: [
        { name: 'Attribution', id: 'attribution', children: [t('GA4', 'ga4'), t('Triple\nWhale', 'triple_whale'), t('Northbeam', 'northbeam'), t('Rockerbox', 'rockerbox')] },
        { name: 'CRO', id: 'cro', children: [t('Optimizely', 'optimizely_cro'), t('VWO', 'vwo'), t('A/B\nTesting', 'ab_testing'), t('Multivariate', 'multivariate')] },
        { name: 'Dashboards', id: 'dataviz', children: [t('Looker', 'looker'), t('Tableau', 'tableau'), t('Power BI', 'power_bi'), t('Looker\nStudio', 'looker_studio')] },
        { name: 'Cohort\nAnalysis', id: 'cohort', children: [t('Mixpanel', 'mixpanel'), t('Amplitude', 'amplitude'), t('Heap', 'heap'), t('SQL', 'sql_cohort')] },
        { name: 'CLV / LTV', id: 'cltv', children: [t('Shopify\nAnalytics', 'shopify_an'), t('Klaviyo\nLTV', 'klaviyo_ltv'), t('ChartMogul', 'chartmogul'), t('SQL LTV', 'sql_ltv')] },
        { name: 'Heatmaps', id: 'heatmap', children: [t('Hotjar', 'hotjar'), t('MS Clarity', 'ms_clarity'), t('FullStory', 'fullstory'), t('SessionCam', 'sessioncam')] },
        { name: 'Revenue\nAnalytics', id: 'revenue', children: [t('HubSpot\nRevenue', 'hubspot_rev'), t('Baremetrics', 'baremetrics'), t('Stripe\nAnalytics', 'stripe_an'), t('Salesforce', 'salesforce_rev')] },
      ]
    },
    {
      name: 'Brand', id: 'brand', children: [
        { name: 'Visual\nIdentity', id: 'identity', children: [t('Figma', 'figma_brand'), t('Brand\nGuidelines', 'brand_guidelines'), t('Canva\nBrand', 'canva_brand'), t('Adobe CC', 'adobe_cc')] },
        { name: 'Brand\nVoice', id: 'voice', children: [t('TOV Doc', 'tov_doc'), t('Style\nGuide', 'style_guide'), t('Jasper', 'jasper'), t('Grammarly', 'grammarly')] },
        { name: 'PR &\nComms', id: 'pr', children: [t('Muck Rack', 'muck_rack'), t('Cision', 'cision'), t('Meltwater', 'meltwater'), t('PRWeb', 'prweb')] },
        { name: 'Events', id: 'events', children: [t('Eventbrite', 'eventbrite'), t('Cvent', 'cvent'), t('Splash', 'splash'), t('Hopin', 'hopin_ev')] },
        { name: 'Partnerships', id: 'collab', children: [t('Co-\nMarketing', 'co_marketing'), t('Joint\nWebinars', 'joint_webinar'), t('Bundle\nDeals', 'bundle_deals'), t('MDF', 'mdf')] },
        { name: 'Storytelling', id: 'storytelling', children: [t('StoryBrand', 'storybrand'), t('Hero/Hub\n/Help', 'hero_hub'), t('Brand\nStory', 'brand_story'), t('Narrative\nArc', 'narrative_arc')] },
        { name: 'Trust &\nProof', id: 'trust', children: [t('G2', 'g2_trust'), t('Trustpilot', 'trustpilot'), t('Capterra', 'capterra'), t('Video\nTestimonials', 'video_test')] },
        { name: 'Cultural\nMktg', id: 'cultural_mktg', children: [t('Trend\nHijacking', 'trend_hijack'), t('Meme\nMarketing', 'meme_mktg'), t('Cultural\nMoments', 'cultural_moments'), t('Subculture\nTarget', 'subculture')] },
      ]
    },
    {
      name: 'Channels', id: 'channels', children: [
        { name: 'Organic\nSearch', id: 'organic', children: [t('Google\nSGE', 'google_sge'), t('Featured\nSnippets', 'featured_snip'), t('People\nAlso Ask', 'paa'), t('Bing', 'bing_org')] },
        { name: 'Direct', id: 'direct', children: [t('Brand\nRecall', 'brand_recall'), t('Email\nSignature', 'email_sig'), t('Bookmarks', 'bookmarks'), t('QR Code', 'qr_code')] },
        { name: 'Referral', id: 'referral', children: [t('Guest\nPosts', 'guest_posts'), t('Backlinks', 'backlinks'), t('PR\nMentions', 'pr_mentions'), t('Podcast\nRef', 'podcast_ref')] },
        { name: 'Push &\nSMS', id: 'push', children: [t('OneSignal', 'onesignal'), t('Klaviyo\nSMS', 'klaviyo_sms'), t('Attentive', 'attentive'), t('Postscript', 'postscript')] },
        { name: 'Influencer', id: 'influencer', children: [t('AspireIQ', 'aspireiq'), t('Upfluence', 'upfluence'), t('Creator.co', 'creator_co'), t('TikTok\nCreator', 'tiktok_creator')] },
        { name: 'Marketplaces', id: 'marketplace', children: [t('Amazon\nDSP', 'amazon_dsp'), t('G2 Profile', 'g2_profile'), t('ASO', 'app_store_aso'), t('Capterra', 'capterra_ch')] },
        { name: 'Messaging\nApps', id: 'msg_apps', children: [t('WhatsApp', 'whatsapp_biz'), t('Telegram', 'telegram_biz'), t('Messenger', 'fb_messenger'), t('iMessage', 'imessage_mktg'), t('Line', 'line_app'), t('WeChat', 'wechat_biz')] },
        { name: 'Chat &\nSupport', id: 'chat', children: [t('Intercom', 'intercom'), t('Drift', 'drift'), t('ManyChat', 'manychat'), t('WhatsApp\nAPI', 'whatsapp_api')] },
        { name: 'Broadcast\nChannels', id: 'broadcast_ch', children: [t('Telegram\nChannels', 'telegram_ch'), t('WhatsApp\nChannels', 'whatsapp_ch'), t('Instagram\nBC', 'ig_broadcast'), t('LinkedIn\nNewsletter', 'li_newsletter'), t('Facebook\nGroups', 'fb_groups_ch'), t('Substack\nBroadcast', 'substack_ch')] },
        { name: 'Social\nDiscovery', id: 'social_disc', children: [t('TikTok\nSearch', 'tiktok_search'), t('Pinterest\nSearch', 'pinterest_search'), t('YouTube\nSearch', 'yt_search'), t('Reddit\nThreads', 'reddit_seo'), t('Quora', 'quora_disc')] },
        { name: 'Video\nPlatforms', id: 'video_platforms', children: [t('YouTube\n(Organic)', 'yt_ch'), t('TikTok\n(Organic)', 'tiktok_ch'), t('Instagram\nReels', 'reels_ch'), t('Twitch', 'twitch_ch'), t('YouTube\nShorts', 'yt_shorts_ch'), t('Kick', 'kick_stream')] },
        { name: 'Dark\nSocial', id: 'dark_social', children: [t('WhatsApp\nSharing', 'whatsapp_share'), t('Slack\nCommunities', 'slack_dark'), t('Telegram', 'telegram_dark'), t('Private\nDiscord', 'discord_dark')] },
        { name: 'Emerging\nChannels', id: 'emerging_ch', children: [t('Threads', 'threads_ch'), t('Bluesky', 'bluesky_ch'), t('Lemon8', 'lemon8_ch'), t('BeReal', 'bereal_ch')] },
      ]
    },
    {
      name: 'Paid\nMedia', id: 'paid', children: [
        { name: 'PPC &\nSearch', id: 'ppc', children: [t('Google\nAds', 'google_ads_p'), t('Bing Ads', 'bing_ads_p'), t('RSAs', 'rsa'), t('Perf.\nMax', 'pmax')] },
        { name: 'Social\nAds', id: 'social_ads', children: [t('Meta Ads', 'meta_ads'), t('LinkedIn\nAds', 'linkedin_ads'), t('TikTok\nAds', 'tiktok_ads'), t('X Ads', 'x_ads')] },
        { name: 'Display &\nBanner', id: 'display', children: [t('GDN', 'gdn'), t('DV360', 'dv360'), t('Programmatic', 'programmatic'), t('HTML5\nBanners', 'banners')] },
        { name: 'Retargeting', id: 'retargeting', children: [t('Meta\nPixel', 'meta_pixel'), t('Custom\nAudiences', 'custom_aud'), t('RLSA', 'rlsa'), t('Dynamic\nAds', 'dynamic_ads')] },
        { name: 'Native\nAds', id: 'native', children: [t('Outbrain', 'outbrain'), t('Taboola', 'taboola'), t('Yahoo\nGemini', 'yahoo_gem'), t('Sharethrough', 'sharethrough')] },
        { name: 'OTT & CTV', id: 'ott', children: [t('Hulu Ads', 'hulu_ads'), t('Roku', 'roku'), t('MNTN', 'mntn'), t('Trade\nDesk', 'trade_desk')] },
        { name: 'Sponsorships', id: 'sponsorship', children: [t('Newsletter\nAds', 'newsletter_sp'), t('Podcast\nSponsors', 'podcast_sp'), t('Naming\nRights', 'event_naming'), t('Team\nBranding', 'shirt_brand')] },
      ]
    },
    {
      name: 'Community', id: 'community', children: [
        { name: 'Community\nPlatforms', id: 'forum', children: [t('Discord', 'discord'), t('Circle.so', 'circle'), t('Discourse', 'discourse_forum'), t('Bettermode', 'bettermode')] },
        { name: 'Social\nCommunities', id: 'social_communities', children: [t('Facebook\nGroups', 'fb_groups'), t('Reddit\nSubs', 'reddit_subs'), t('Slack\nCommunity', 'slack_com'), t('Mighty\nNetworks', 'mighty_networks')] },
        { name: 'Brand\nAdvocates', id: 'advocacy', children: [t('Advocate\nPortal', 'advocate_portal'), t('Review\nIncentives', 'review_inc'), t('Beta\nProgram', 'beta_group'), t('VIP Access', 'vip_access')] },
        { name: 'Loyalty &\nRewards', id: 'loyalty', children: [t('Points\nSystem', 'points_sys'), t('VIP Tiers', 'vip_tiers'), t('Cashback', 'cashback'), t('Surprise &\nDelight', 'surprise_delight')] },
        { name: 'NPS &\nCSAT', id: 'nps', children: [t('Delighted', 'delighted'), t('Typeform', 'typeform_nps'), t('SurveyMonkey', 'surveymonkey'), t('Medallia', 'medallia')] },
        { name: 'Ambassador\nPrograms', id: 'ambassador', children: [t('LoudCrowd', 'loudcrowd'), t('Student\nAmbassadors', 'student_amb'), t('Talkable', 'talkable'), t('Extole', 'extole')] },
        { name: 'Referral\nPrograms', id: 'referral_prog', children: [t('ReferralHero', 'referralhero'), t('Viral\nLoops', 'viral_loops'), t('Friendbuy', 'friendbuy'), t('Yotpo', 'yotpo')] },
      ]
    },
    {
      name: 'Physical', id: 'physical', children: [
        { name: 'Product\nSampling', id: 'sampling', children: [t('Street\nTeams', 'street_teams'), t('Sub Box\nInserts', 'sub_box'), t('Sampling\nEvents', 'sampling_ev'), t('Direct\nPost', 'direct_post')] },
        { name: 'Retail\nStores', id: 'retail', children: [t('Planogram', 'planogram'), t('End-Cap\nDisplay', 'end_cap'), t('POS\nMaterials', 'pos_mat'), t('Shelf\nTalkers', 'shelf_talker')] },
        { name: 'Brand\nRetail', id: 'brand_store', children: [t('Flagship\nStore', 'flagship'), t('Shop-in-\nShop', 'shop_in_shop'), t('Concession', 'concession'), t('Pop-In', 'pop_in')] },
        { name: 'Pop-Up\nShops', id: 'popup', children: [t('Container\nStore', 'container_store'), t('Market\nStall', 'market_stall'), t('Brand\nTakeover', 'brand_takeover'), t('Collab\nPop-Up', 'collab_popup')] },
        { name: 'Festivals', id: 'festivals', children: [t('Festival\nBooth', 'festival_booth'), t('Branded\nStage', 'branded_stage'), t('Wristband\nSponsor', 'wristband_sp'), t('On-Site\nSampling', 'onsite_sampling')] },
        { name: 'OOH &\nBillboards', id: 'ooh', children: [t('Billboards', 'static_bill'), t('Transit\nAds', 'transit_ads'), t('Wild\nPosting', 'wild_posting'), t('Bus Wraps', 'bus_wraps')] },
        { name: 'Experiential', id: 'experiential', children: [t('Brand\nActivation', 'brand_act'), t('AR\nExperience', 'ar_exp'), t('Flash Mob', 'flash_mob'), t('Immersive\nInstall', 'immersive_inst')] },
        { name: 'DOOH', id: 'dooh', children: [t('Clear\nChannel', 'clear_channel'), t('Lamar', 'lamar'), t('Broadsign', 'broadsign'), t('Prog.\nDOOH', 'prog_dooh')] },
        { name: 'Direct\nMail', id: 'direct_mail', children: [t('Postcard', 'postcard'), t('Catalogue', 'catalogue'), t('Lumpy\nMail', 'lumpy_mail'), t('Dimensional', 'dimensional')] },
        { name: 'Trade\nShows', id: 'trade_show', children: [t('Booth\nDesign', 'booth_design'), t('Demo\nStations', 'demo_station'), t('Lead\nCapture', 'lead_forms'), t('Speaking\nSlots', 'speaking')] },
        { name: 'In-Store\nExp.', id: 'in_store_exp', children: [t('Kiosks', 'kiosk'), t('Sampling\nStations', 'samp_station'), t('Digital\nSignage', 'dig_signage'), t('Staff\nDemos', 'staff_demo')] },
        { name: 'Packaging', id: 'packaging', children: [t('Unboxing\nDesign', 'unboxing_des'), t('On-Pack\nQR', 'qr_pack'), t('Sustainable\nPack', 'sustain_pack'), t('Custom\nInsert', 'custom_insert')] },
        { name: 'Guerrilla\nMktg', id: 'guerrilla', children: [t('Chalk Art', 'chalk_art'), t('Ambient\nMedia', 'ambient'), t('Projection\nMapping', 'proj_map'), t('Brand\nStunt', 'stunt')] },
      ]
    },
    {
      name: 'Product\nGrowth', id: 'product_growth', children: [
        { name: 'PLG\nMechanics', id: 'plg_mech', children: [t('June.so', 'june_so'), t('Pendo', 'pendo'), t('PostHog', 'posthog'), t('Product\nFruits', 'product_fruits')] },
        { name: 'Onboarding', id: 'onboarding', children: [t('Appcues', 'appcues'), t('UserPilot', 'userpilot'), t('Chameleon', 'chameleon'), t('Intercom\nTours', 'intercom_tours')] },
        { name: 'Feature\nAdoption', id: 'feature_adopt', children: [t('Gainsight\nPX', 'gainsight_px'), t('LaunchDarkly', 'launchdarkly'), t('Whatfix', 'whatfix'), t('WalkMe', 'walkme')] },
        { name: 'In-Product\nMessaging', id: 'product_msg_tactic', children: [t('Braze', 'braze_plg'), t('OneSignal', 'onesig_plg'), t('Userflow', 'userflow'), t('In-App\nBanners', 'in_app_banners')] },
        { name: 'Release\nMarketing', id: 'release_mktg', children: [t('Beamer', 'beamer'), t('Productboard', 'productboard'), t('Noticeable', 'noticeable'), t('Canny', 'canny')] },
        { name: 'Growth\nLoops', id: 'growth_loops', children: [t('Viral\nReferral', 'viral_ref'), t('Network\nEffects', 'network_effects'), t('Content\nLoops', 'content_loops'), t('Integration\nLoops', 'integration_loops')] },
        { name: 'Activation\nOptimisation', id: 'activation', children: [t('Sprig', 'sprig'), t('Glassbox', 'glassbox'), t('Contentsquare', 'contentsquare'), t('Indicative', 'indicative')] },
        { name: 'Freemium\nStrategy', id: 'freemium_tactic', children: [t('Freemium\nModel', 'freemium_model'), t('Trial\nFlows', 'trial_flows'), t('Feature\nGates', 'feature_gates'), t('Usage\nLimits', 'usage_limits')] },
      ]
    },
    {
      name: 'Lifecycle', id: 'lifecycle', children: [
        { name: 'Lifecycle\nStrategy', id: 'lifecycle_strat_tactic', children: [t('Journey\nMapping', 'journey_map'), t('Stage\nDefinition', 'lifecycle_stages'), t('CLV\nModelling', 'clv_model'), t('Cohort\nPlanning', 'cohort_plan')] },
        { name: 'Retention\nMarketing', id: 'retention_tactic', children: [t('Braze', 'braze_ret'), t('Iterable', 'iterable'), t('Customer.io', 'customer_io'), t('Klaviyo', 'klaviyo_ret')] },
        { name: 'Win-Back\nCampaigns', id: 'winback_tactic', children: [t('Win-Back\nSeries', 'winback_series'), t('Discount\nCode', 'discount_code'), t('Personal\nReach', 'personal_reach'), t('Sunset\nFlow', 'sunset_flow')] },
        { name: 'Upsell &\nCross-Sell', id: 'upsell_tactic', children: [t('In-App\nUpsell', 'in_app_upsell'), t('Email\nUpsell', 'email_upsell'), t('Usage\nTriggers', 'usage_trigger'), t('Sales\nHandoff', 'sales_handoff')] },
        { name: 'Churn\nPrevention', id: 'churn_prev_tactic', children: [t('ChurnZero', 'churnzero'), t('Gainsight', 'gainsight'), t('Health\nScoring', 'health_score'), t('Cancel\nFlow', 'cancel_flow')] },
        { name: 'Customer\nEducation', id: 'cust_edu_tactic', children: [t('Onboard\nEmail', 'onboard_email'), t('Help\nCentre', 'help_center'), t('Certification', 'certification'), t('Edu\nWebinars', 'webinar_edu')] },
        { name: 'Subscription\nLifecycle', id: 'sub_lifecycle_tactic', children: [t('Renewal\nEmails', 'renewal_emails'), t('Pause\nFlow', 'pause_flow'), t('Downgrade\nPath', 'downgrade_path'), t('Annual\nConversion', 'annual_push')] },
      ]
    },
    {
      name: 'Mobile', id: 'mobile', children: [
        { name: 'ASO', id: 'aso_tactic', children: [t('App\nKeywords', 'app_keywords'), t('Screenshots', 'screenshots'), t('Preview\nVideo', 'preview_video'), t('Rating\nCampaigns', 'rating_camp')] },
        { name: 'App Install\nAds', id: 'app_install_tactic', children: [t('Apple\nSearch Ads', 'apple_search_ads'), t('Google\nUAC', 'google_uac'), t('Meta\nApp Ads', 'meta_app'), t('TikTok\nApp Ads', 'tiktok_app')] },
        { name: 'In-App\nMessaging', id: 'in_app_msg_tactic', children: [t('Braze', 'braze_mob'), t('Airship', 'airship'), t('Firebase', 'firebase_mob'), t('Leanplum', 'leanplum')] },
        { name: 'Deep\nLinking', id: 'deep_link_tactic', children: [t('Branch.io', 'branch'), t('AppsFlyer\nDL', 'appsflyer'), t('Firebase\nLinks', 'firebase_dl'), t('Kochava', 'kochava')] },
        { name: 'Mobile\nAttribution', id: 'mobile_attr_tactic', children: [t('AppsFlyer', 'appsflyer_attr'), t('Adjust', 'adjust'), t('Branch', 'branch_attr'), t('Singular', 'singular')] },
        { name: 'App\nRetention', id: 'app_retention_tactic', children: [t('Push\nRe-Engage', 'push_reengage'), t('In-App\nNotif', 'in_app_notif'), t('Win-Back\nMob', 'winback_mob'), t('Feature\nAnnounce', 'feature_ann')] },
        { name: 'Mobile\nOnboarding', id: 'mobile_onboard_tactic', children: [t('Appcues\nMobile', 'appcues_mob'), t('UXCam', 'uxcam'), t('Braze\nCanvas', 'braze_canvas'), t('Onboard\nFlows', 'onboard_flows')] },
      ]
    },
    {
      name: 'Earned\nMedia', id: 'earned_media', children: [
        { name: 'Editorial\nPlacements', id: 'editorial_tactic', children: [t('Press\nPitching', 'press_pitch'), t('Story\nAngles', 'story_angles'), t('Journalist\nDB', 'journalist_db'), t('News\nHooks', 'news_hook')] },
        { name: 'Expert\nCommentary', id: 'expert_comment_tactic', children: [t('HARO', 'haro_earn'), t('Qwoted', 'qwoted'), t('Expert\nRoundups', 'expert_roundups'), t('Commentary\nPitches', 'commentary_pitch')] },
        { name: 'Thought\nLeadership', id: 'thought_lead_tactic', children: [t('LinkedIn\nArticles', 'linkedin_tl'), t('Industry\nPubs', 'industry_pubs'), t('Conf.\nSpeaking', 'conf_speaking'), t('Guest\nColumns', 'guest_cols')] },
        { name: 'Podcast\nGuesting', id: 'pod_guesting_tactic', children: [t('Rephonic', 'rephonic'), t('Podchaser', 'podchaser_earn'), t('Guest\nOne-Sheet', 'guest_sheet'), t('Pitch\nTemplates', 'pitch_temp')] },
        { name: 'Media\nPartnerships', id: 'media_partner_tactic', children: [t('Sponsored\nEditorial', 'sponsored_ed'), t('Joint\nResearch', 'joint_research'), t('White\nPapers', 'white_papers'), t('Co-\nCreation', 'co_creation')] },
        { name: 'Awards &\nRankings', id: 'awards_tactic', children: [t('Award\nSubs', 'award_subs'), t('Best-Of\nLists', 'best_of_lists'), t('Analyst\nBriefs', 'analyst_briefs'), t('Rankings', 'rankings')] },
        { name: 'Analyst\nRelations', id: 'analyst_rel_tactic', children: [t('Gartner', 'gartner'), t('Forrester', 'forrester'), t('IDC', 'idc'), t('Magic\nQuadrant', 'magic_quadrant')] },
      ]
    },
    {
      name: 'Growth\nLab', id: 'growth_lab', children: [
        { name: 'North Star\nMetric', id: 'north_star_tactic', children: [t('North Star\nFramework', 'north_star_metric'), t('AARRR\nFunnel', 'aarrr'), t('Sean Ellis\nTest', 'sean_ellis'), t('Retention\nCurve', 'retention_curve')] },
        { name: 'Viral\nMechanics', id: 'viral_mech_tactic', children: [t('K-Factor', 'k_factor'), t('Viral\nCoefficient', 'viral_coeff'), t('Loop\nMapping', 'loop_mapping'), t('Mechanism\nDesign', 'mechanism_design')] },
        { name: 'Growth\nSprints', id: 'growth_sprint_tactic', children: [t('Growth\nSprints', 'growth_sprints'), t('Channel\nExperiments', 'channel_experiments'), t('Distribution\nHacks', 'distrib_hacks'), t('Scrappy\nTests', 'scrappy_tests')] },
        { name: 'Experiment\nTracking', id: 'exp_tracking_tactic', children: [t('ICE\nScoring', 'ice_scoring'), t('PIE\nScoring', 'pie_scoring'), t('Hypothesis\nDoc', 'hypothesis_doc'), t('Exp.\nBacklog', 'exp_backlog')] },
        { name: 'Landing Page\nTests', id: 'rapid_test_tactic', children: [t('Unbounce', 'unbounce_gl'), t('Instapage', 'instapage'), t('Convert.com', 'convert_exp'), t('Webflow', 'webflow_lp')] },
        { name: 'Messaging\nExperiments', id: 'msg_test_tactic', children: [t('Copy\nTesting', 'copy_testing'), t('Subject\nLine A/B', 'subject_ab'), t('CTA\nExperiments', 'cta_exp'), t('Value Prop\nTesting', 'vp_testing')] },
        { name: 'Mix\nModelling', id: 'channel_exp_tactic', children: [t('Mix\nModelling', 'mix_model'), t('Meridian /\nRobyn', 'mmm_tool'), t('Budget\nAllocation', 'budget_alloc'), t('Cross-Ch.\nAttribution', 'cross_ch_attr')] },
      ]
    },
    {
      name: 'Data\nInfra', id: 'data_infra', children: [
        { name: 'CDP', id: 'cdp_tactic', children: [t('Segment', 'segment'), t('mParticle', 'mparticle'), t('Tealium', 'tealium'), t('Lytics', 'lytics')] },
        { name: 'Data\nWarehouse', id: 'warehouse_tactic', children: [t('Snowflake', 'snowflake'), t('BigQuery', 'bigquery'), t('Redshift', 'redshift'), t('Databricks', 'databricks')] },
        { name: 'Identity\nResolution', id: 'identity_res_tactic', children: [t('LiveRamp', 'liveramp'), t('Neustar', 'neustar'), t('FullContact', 'fullcontact'), t('Merkle', 'merkle')] },
        { name: 'Event\nTracking', id: 'event_track_tactic', children: [t('Segment\nEvents', 'seg_events'), t('GA4\nEvents', 'ga4_events'), t('Custom\nTaxonomy', 'custom_tax'), t('Amplitude\nSDK', 'amplitude_sdk')] },
        { name: 'Server-Side\nTracking', id: 'server_track_tactic', children: [t('Server\nGTM', 'server_gtm'), t('Stape', 'stape'), t('Conversion\nAPI', 'conversion_api'), t('1st Party\nData', 'first_party')] },
        { name: 'Privacy &\nConsent', id: 'privacy_mgmt_tactic', children: [t('OneTrust', 'onetrust'), t('Cookiebot', 'cookiebot'), t('TrustArc', 'trustarc'), t('CMP\nSetup', 'cmp_setup')] },
        { name: 'Data\nGovernance', id: 'data_catalog_tactic', children: [t('dbt', 'dbt'), t('Atlan', 'atlan'), t('Alation', 'alation'), t('Data\nLineage', 'data_lineage')] },
      ]
    },
    {
      name: 'AI\nMarketing', id: 'ai_marketing', children: [
        { name: 'AI Content\nGeneration', id: 'ai_content_tactic', children: [t('ChatGPT', 'chatgpt'), t('Jasper', 'jasper_ai'), t('Claude\nAPI', 'claude_api'), t('Copy.ai', 'copy_ai')] },
        { name: 'AI Media\nBuying', id: 'ai_media_tactic', children: [t('Meta\nAdvantage+', 'meta_adv'), t('Smart\nBidding', 'smart_bidding_ai'), t('Madgicx', 'madgicx'), t('Revealbot', 'revealbot')] },
        { name: 'AI\nPersonalisation', id: 'ai_personal_tactic', children: [t('Dynamic\nYield', 'dynamic_yield'), t('Monetate', 'monetate'), t('Mutiny', 'mutiny'), t('Personyze', 'personyze')] },
        { name: 'AI\nSegmentation', id: 'ai_seg_tactic', children: [t('Klaviyo\nAI', 'klaviyo_ai'), t('Braze AI', 'braze_ai'), t('Adobe\nRT-CDP', 'adobe_rt_cdp'), t('HubSpot\nAI', 'hubspot_ai')] },
        { name: 'Predictive\nAnalytics', id: 'predictive_tactic', children: [t('MadKudu', 'madkudu'), t('Clearbit', 'clearbit_intent'), t('Qualified', 'qualified_ai'), t('Salesforce\nEinstein', 'salesforce_ei')] },
        { name: 'AI Customer\nSupport', id: 'ai_support_tactic', children: [t('Intercom\nAI', 'intercom_ai'), t('Zendesk\nAI', 'zendesk_ai'), t('Drift AI', 'drift_ai'), t('Ada', 'ada_bot')] },
        { name: 'AI Creative\nTesting', id: 'ai_creative_tactic', children: [t('AdCreative\n.ai', 'adcreative'), t('Pencil', 'pencil'), t('Midjourney', 'midjourney'), t('DALL-E', 'dalle')] },
        { name: 'AI\nRecommendations', id: 'ai_recommend_tactic', children: [t('Nosto', 'nosto'), t('Barilliance', 'barilliance'), t('LimeSpot', 'limespoke'), t('Clerk.io', 'clerk_io')] },
      ]
    },
    {
      name: 'Commerce', id: 'commerce', children: [
        { name: 'Conversion\nStrategy', id: 'conv_strat_tactic', children: [t('LP CRO', 'lp_cro'), t('Product\nPage', 'product_page'), t('Cart\nRecovery', 'cart_recovery'), t('Exit\nIntent', 'exit_intent')] },
        { name: 'Merchandising', id: 'merchandising_tactic', children: [t('Visual\nMerch', 'visual_merch'), t('Category\nPages', 'category_pages'), t('Product\nSorting', 'product_sorting'), t('Collections', 'collections')] },
        { name: 'Pricing\nStrategy', id: 'pricing_com_tactic', children: [t('Dynamic\nPricing', 'dynamic_pricing'), t('Price\nTesting', 'price_testing'), t('Tiered\nPricing', 'tiered_pricing'), t('Anchor\nPricing', 'anchor_pricing')] },
        { name: 'Promotions', id: 'promotions_tactic', children: [t('Flash\nSales', 'flash_sales'), t('BOGO', 'bogo'), t('Seasonal\nPromos', 'seasonal_promos'), t('Loyalty\nDiscounts', 'loyalty_disc')] },
        { name: 'Bundles &\nOffers', id: 'bundles_tactic', children: [t('Product\nBundling', 'product_bundling'), t('Cross-Sell\nOffers', 'cross_sell'), t('Bundle\nLanding Pg', 'bundle_lps'), t('Kit\nBuilding', 'kit_build')] },
        { name: 'Checkout\nOptimisation', id: 'checkout_opt_tactic', children: [t('1-Click\nCheckout', 'one_click'), t('Guest\nCheckout', 'guest_checkout'), t('BNPL', 'bnpl'), t('Checkout\nA/B', 'checkout_ab')] },
        { name: 'Subscription\nStrategy', id: 'sub_strategy_tactic', children: [t('Recharge', 'recharge'), t('Skio', 'skio'), t('Bold\nSubs', 'bold_sub'), t('Recurly', 'recurly')] },
        { name: 'Marketplace\nOpt.', id: 'marketplace_opt_tactic', children: [t('Amazon\nListing', 'amazon_list'), t('Review\nStrategy', 'review_strat'), t('Sponsored\nPlacements', 'sponsored_plac'), t('A+ Content', 'aplus_content')] },
      ]
    },
    {
      name: 'Demand\nGen', id: 'demand_gen', children: [
        { name: 'ABM', id: 'abm_tactic', children: [t('6sense', 'sixsense_dg'), t('Demandbase', 'demandbase_dg'), t('Terminus', 'terminus'), t('RollWorks', 'rollworks')] },
        { name: 'Intent\nData', id: 'intent_data_tactic', children: [t('Bombora', 'bombora_dg'), t('G2 Intent', 'g2_intent'), t('TechTarget', 'techtarget'), t('Aberdeen', 'aberdeen')] },
        { name: 'Sales\nEnablement', id: 'sales_enable_tactic', children: [t('Highspot', 'highspot'), t('Seismic', 'seismic'), t('Showpad', 'showpad'), t('Guru', 'guru')] },
        { name: 'Lead\nScoring', id: 'lead_scoring_tactic', children: [t('HubSpot\nScoring', 'hubspot_score'), t('Marketo\nMQL', 'marketo_mql'), t('Predictive\nScoring', 'pred_scoring'), t('SQL\nDefinition', 'sql_def')] },
        { name: 'SDR\nSupport', id: 'sdr_support_tactic', children: [t('Apollo.io', 'apollo'), t('Outreach', 'outreach'), t('Salesloft', 'salesloft'), t('LinkedIn\nSales Nav', 'linkedin_sn')] },
        { name: 'Pipeline\nMarketing', id: 'pipeline_mktg_tactic', children: [t('Pipeline\nAcceleration', 'pipeline_acc'), t('Deal\nSupport', 'deal_support'), t('Exec\nOutreach', 'exec_outreach'), t('Champion\nMktg', 'champion_mktg')] },
        { name: 'Field\nMarketing', id: 'field_mktg_tactic', children: [t('Regional\nEvents', 'regional_ev'), t('Roundtables', 'roundtables')] }
      ]
    }
  ]
};
